trigger:
  branches:
    include:
      - main

variables:
  imageName: 'dotnet-docker-app'

stages:
- stage: Build
  displayName: Build and Push to ACR
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '7.0.x'

    - script: |
        cd app
        dotnet restore
        dotnet publish -c Release -o ../out
      displayName: 'Build .NET Project'

    - task: Docker@2
      inputs:
        containerRegistry: 'myACRConnection'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          latest

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'myAzureConnection'
        appName: 'my-dotnet-app'
        containers: 'myacrname.azurecr.io/$(imageName):latest'
